name: examples/subscriber

parameters:
  subscription_key:
    description: Key used to define this subscriber
    default: subscriber

dependencies:
  examples/gcp-pubsub: latest
  examples/publisher: latest

services:
  api:
    build:
      context: ./
    environment:
      PUBSUB_ENDPOINT: ${{ dependencies['examples/gcp-pubsub'].interfaces.pubsub.url }}
      GCP_PROJECT_ID: ${{ dependencies['examples/gcp-pubsub'].outputs.gcp_project_id }}
      PUBSUB_TOPIC: ${{ dependencies['examples/publisher'].outputs.publish_topic }}
      PUBSUB_SUBSCRIPTION: ${{ parameters.subscription_key }}
