name: subscriber

secrets:
  subscription_key:
    description: Key used to define this subscriber
    default: subscriber

dependencies:
  gcp-pubsub: latest
  publisher: latest

services:
  api:
    build:
      context: ./
    environment:
      PUBSUB_ENDPOINT: ${{ dependencies['gcp-pubsub'].services.pubsub.interfaces.main.url }}
      GCP_PROJECT_ID: ${{ dependencies['gcp-pubsub'].outputs.gcp_project_id }}
      PUBSUB_TOPIC: ${{ dependencies['publisher'].outputs.publish_topic }}
      PUBSUB_SUBSCRIPTION: ${{ secrets.subscription_key }}
