name: stateless-component
description: A component without its own database or state. This shows how to connect to dependencies to serve business logic.
homepage: https://github.com/architect-team/architect-cli/tree/master/examples/stateless-component
keywords:
  - architect
  - examples
  - stateless
  - dependencies
  - nextjs
  - reactjs

parameters:
  log_level:
    default: debug
    description: |
      Applied as an environment variable to each service in the component
      (oneof: ['error', 'warning', 'debug', 'info', 'trace'])

dependencies:
  hello-world: latest

services:
  stateless-app:
    build:
      context: ./
    interfaces:
      http: 8080
    environment:
      LOG_LEVEL: ${{ parameters.log_level }}
      HELLO_WORLD_ADDR: ${{ dependencies['examples/hello-world'].interfaces.hello.url }}

interfaces:
  frontend:
    description: Exposes the app to upstream traffic
    url: ${{ services.stateless-app.interfaces.http.url }}
