description: Easily register and deploy a component to a new environment on the Architect Cloud, then destroy the component and environment when ready

display:
  home_url: https://architect.io
  source_url: https://github.com/architect-team/architect-cli/tree/master/circleci-orbs

jobs:
  create:
    parameters:
      email:
        type: string
      account:
        type: string
      environment:
        type: string
        default: ''
      platform:
        type: string
      component_name:
        type: string
      component_file:
        type: string
        default: ./architect.yml
      deploy_flags:
        type: string
        default: ''
    executor: preview_executor
    steps:
      - run: |
          if [ "<< parameters.environment >>" = "" ]; then
            GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
            EXPORT_ENV_STR='export ENVIRONMENT_NAME='preview-$GIT_BRANCH
            echo $EXPORT_ENV_STR >> $BASH_ENV
          else
            echo 'export ENVIRONMENT_NAME=<< parameters.environment >>' >> $BASH_ENV
          fi
      - run: npm install -g @architect-io/cli@0.7.5
      - run: architect login -e << parameters.email >>
      - run: architect register << parameters.component_file >> -t ${ENVIRONMENT_NAME}
      - run: architect environment:create ${ENVIRONMENT_NAME} -a << parameters.account >> --platform << parameters.platform >>
      - run: architect deploy --auto_approve -a << parameters.account >> -e ${ENVIRONMENT_NAME} << parameters.component_name >>:${ENVIRONMENT_NAME} << parameters.deploy_flags >>
  destroy:
    parameters:
      email:
        type: string
      account:
        type: string
      environment:
        type: string
        default: ''
      component_name:
        type: string
    executor: preview_executor
    steps:
      - run: |
          if [ "<< parameters.environment >>" = "" ]; then
            GIT_BRANCH=$(git log --first-parent --merges -1 --oneline | cut -d'/' -f2)
            EXPORT_ENV_STR='export ENVIRONMENT_NAME='preview-$GIT_BRANCH
            echo $EXPORT_ENV_STR >> $BASH_ENV
          else
            echo 'export ENVIRONMENT_NAME=<< parameters.environment >>' >> $BASH_ENV
          fi
      - run: npm install -g @architect-io/cli@0.7.5
      - run: architect login -e << parameters.email >>
      - run: architect destroy --auto_approve -a << parameters.account >> -e ${ENVIRONMENT_NAME} -c << parameters.component_name >>:${ENVIRONMENT_NAME}
      - run: architect env:destroy --auto_approve ${ENVIRONMENT_NAME} -a << parameters.account >>

executors:
  preview_executor:
    machine:
      image: ubuntu-1604:202007-01

examples:
  create_preview:
    description: Create a preview environment on the Architect Cloud by deploying the component to the specified environment
    usage:
      version: "2.1"
      orbs:
        preview: architect-team/preview@0.7.5
      workflows:
        build_test_deploy:
          jobs:
            - preview/create:
                filters:
                  branches:
                    ignore:
                      - master
                pre-steps:
                  - checkout
                email: email@gmail.com
                password: $PASSWORD
                account: example-account
                platform: example-platform
                component_name: example-account/hello-world
  destroy_preview:
    description: Destroy the deployed component and the specified environment
    usage:
      version: 2.1
      orbs:
        preview: architect-team/preview@0.7.5
      workflows:
        build_test_deploy:
          jobs:
            - preview/destroy:
                filters:
                  branches:
                    only:
                      - master
                pre-steps:
                  - checkout
                email: email@gmail.com
                password: $PASSWORD
                account: example-account
                component_name: example-account/hello-world

version: 2.1

