name: hello-world
description: A simple hello-world component that returns "Hello World!" on every request.
homepage: https://github.com/architect-team/architect-cli/tree/main/examples/hello-world
keywords:
  - hello-world
  - nodejs
  - architect
  - examples

services:
  api:
    build:
      context: .
    interfaces:
      main:
        port: 3000
        ingress:
          subdomain: hello
