name: hello-world
description: A simple hello-world component that returns "Hello World!" on every request.
homepage: https://github.com/architect-team/architect-cli/tree/master/examples/hello-world
keywords:
  - hello-world
  - nodejs
  - architect
  - examples

services:
  api:
    build:
      context: .
    interfaces:
      main: 3000

interfaces:
  hello:
    description: Connects to the hello-world service to return "Hello World!" on-demand
    url: ${{ services.api.interfaces.main.url }}
    ingress:
      subdomain: hello
