name: database-seeding
description: Example express application using typeorm to seed test data
homepage: https://github.com/architect-team/architect-cli/tree/master/examples/database-seeding
keywords:
  - architect
  - examples
  - postgres
  - nodejs
  - express-js

parameters:
  auto_ddl:
    description: Options are 'none', 'migrate', and 'seed'; none- no ddl; migrate- runs unrun database migrations at application start; seed- runs unrun migrations and test data seeding script at application start
    default: none
  db_user:
    description: Username used to access the database
    default: postgres
  db_pass:
    description: Password used to access the database
    default: architect
  db_name:
    description: Name of the database instance containing the relevant API tables
    default: seeding_demo

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    interfaces:
      main: 3000
    environment:
      DATABASE_HOST: ${{ services.my-demo-db.interfaces.postgres.host }}
      DATABASE_PORT: ${{ services.my-demo-db.interfaces.postgres.port }}
      DATABASE_USER: ${{ services.my-demo-db.environment.POSTGRES_USER }}
      DATABASE_PASSWORD: ${{ services.my-demo-db.environment.POSTGRES_PASSWORD }}
      DATABASE_SCHEMA: ${{ services.my-demo-db.environment.POSTGRES_DB }}
      AUTO_DDL: ${{ parameters.auto_ddl }}

  my-demo-db:
    image: postgres:11
    interfaces:
      postgres: 5432
    environment:
      POSTGRES_DB: ${{ parameters.db_name }}
      POSTGRES_USER: ${{ parameters.db_user }}
      POSTGRES_PASSWORD: ${{ parameters.db_pass }}

interfaces:
  main:
    description: Exposes the app to upstream traffic
    url: ${{ services.app.interfaces.main.url }}
