name: nestjs-simple
description: Simple NestJS microservice that uses TCP for inter-process communication
homepage: https://github.com/architect-team/architect-cli/tree/master/examples/nestjs-microservices/simple
keywords:
  - nestjs
  - examples
  - tcp
  - microservices

interfaces:
  main:
    url: ${{ services.api.interfaces.main.url }}
    ingress:
      subdomain: api

services:
  api:
    build:
      context: ./
    interfaces:
      main:
        port: 8080
        protocol: tcp
    ${{ if architect.environment == 'local' }}:
      command: npm run start:dev
      volumes:
        src:
          host_path: ./src/
          mount_path: /usr/src/app/src/
