name: nestjs-simple
description: Simple NestJS microservice
homepage: https://github.com/architect-team/architect-cli/tree/main/examples/nestjs-microservices/simple
keywords:
  - nestjs
  - examples
  - microservices

interfaces:
  main:
    url: ${{ services.api.interfaces.main.url }}
    ingress:
      subdomain: api

services:
  api:
    build:
      context: ./
      args:
        NODE_ENV: production
    interfaces:
      main:
        port: 8080
    debug:
      command: npm run start:dev
      build:
        args:
          NODE_ENV: development
      volumes:
        src:
          host_path: ./src/
          mount_path: /usr/src/app/src/
