#!/bin/sh

echo "\nValidating Javascript:\n"

if ! npm run check:git; then
  echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
  exit 1
else
  echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi

echo "\nJavascript validation completed!\n"
