name: fusionauth
description: An example fusion auth Architect component
homepage: https://github.com/architect-team/architect-cli/tree/master/examples/fusionauth

parameters:
  db_name:
    description: Name of the database containing FusionAuth tables
    default: fusionauth
  root_db_user:
    description: Root database user. Should only be used for running migrations.
    default: root
  root_db_pass:
    description: Root database password. Should only be used for running migrations.
    default: secret
  fusionauth_db_user:
    description: Username used by FusionAuth to regularly access the database
    default: ${{ parameters.root_db_user }}
  fusionauth_db_pass:
    description: Username used by FusionAuth to regularly access the database
    default: ${{ parameters.root_db_pass }}
  fusionauth_memory:
    description: Memory to allocate to the FusionAuth JVM
    default: 512M
  default_api_key:
    description: API key to seed with the FusionAuth instance. Used to dynamically generate oauth clients at deploy-time.
    default: 4600268f-5408-4cb5-8298-5407703713f3
  admin_user_email:
    description: Email address of the default admin user
    default: test@test.com
  admin_user_password:
    description: Password for the default admin user
    default: password
  fusionauth_db_host:
    required: true

interfaces:
  app:
    description: Exposes the fusionauth app to upstream traffic
    url: ${{ services.fusionauth.interfaces.public.url }}
    ingress:
      subdomain: app

services:
  fusionauth-db:
    image: postgres:9.6
    interfaces:
      postgres:
        protocol: postgresql
        port: 5432
        host: ${{ parameters.fusionauth_db_host }}
    environment:
      POSTGRES_USER: ${{ parameters.root_db_user }}
      POSTGRES_PASSWORD: ${{ parameters.root_db_pass }}
      POSTGRES_DB: ${{ parameters.db_name }}

  fusionauth:
    image: fusionauth/fusionauth-app:latest
    interfaces:
      public: 9011
    environment:
      DATABASE_URL: jdbc:${{ services.fusionauth-db.interfaces.postgres.url }}/${{ parameters.db_name }}
      DATABASE_ROOT_USER: ${{ parameters.root_db_user }}
      DATABASE_ROOT_PASSWORD: ${{ parameters.root_db_pass }}
      DATABASE_USER: ${{ parameters.fusionauth_db_user }}
      DATABASE_PASSWORD: ${{ parameters.fusionauth_db_pass }}
      FUSIONAUTH_MEMORY: ${{ parameters.fusionauth_memory }}
      FUSIONAUTH_SEARCH_ENGINE_TYPE: database
      FUSIONAUTH_URL: ${{ interfaces.app.url }}
      FUSIONAUTH_RUNTIME_MODE: development
      FUSIONAUTH_API_KEY: ${{ parameters.default_api_key }}
      ADMIN_USER_EMAIL: ${{ parameters.admin_user_email }}
      ADMIN_USER_PASSWORD: ${{ parameters.admin_user_password }}
      KICKSTART_CONTENTS: file:./config/kickstart.json
      FUSIONAUTH_KICKSTART: /usr/local/fusionauth/kickstart.json
      FUSIONAUTH_APP_SILENT_MODE: false
    command:
      - sh
      - -c
      - |
        echo "$KICKSTART_CONTENTS" > $FUSIONAUTH_KICKSTART
        chmod 755 $FUSIONAUTH_KICKSTART
        /usr/local/fusionauth/fusionauth-app/apache-tomcat/bin/catalina.sh run
