name: rabbitmq
description: Example RabbitMQ message broker
homepage: https://github.com/architect-team/architect-cli/tree/main/examples/rabbitmq
keywords:
  - architect
  - examples
  - rabbitmq
  - nodejs
  - python

secrets:
  queue_name:
    default: architect

services:
  message-broker:
    image: rabbitmq:3-management
    interfaces:
      mgmt: 15672
      amqp:
        protocol: amqp
        port: 5672
  producer:
    build:
      context: ./rabbit-producer
      dockerfile: Dockerfile
    interfaces:
      app: 3000
    environment:
      AMQP_HOST: ${{ services.message-broker.interfaces.amqp.host }}
      QUEUE_NAME: ${{ secrets.queue_name }}
    command:
      - sh
      - -c
      - |
        sleep 30
        npm start
  consumer:
    build:
      context: ./rabbit-consumer
      dockerfile: Dockerfile
    environment:
      AMQP_HOST: ${{ services.message-broker.interfaces.amqp.host }}
      QUEUE_NAME: ${{ secrets.queue_name }}
    command:
      - sh
      - -c
      - |
        sleep 30
        python -u consumer.py

interfaces:
  app:
    description: Exposes the producer app
    url: ${{ services.producer.interfaces.app.url }}
    ingress:
      subdomain: app
  mgmt:
    description: Exposes the management app
    url: ${{ services.message-broker.interfaces.mgmt.url }}
    ingress:
      subdomain: admin
