name: scheduled-tasks
description: Example application that calls the API once per 5 minutes and prints the results; showcasing Tasks (cron jobs)
homepage: https://github.com/architect-team/architect-cli/tree/master/examples/scheduled-tasks

tasks:
  curler:
    image: ellerbrock/alpine-bash-curl-ssl # useful public image with bash and curl pre-installed
    schedule: '0 0 * * *' # every day at 12:00am
    command:
      - sh
      - -c
      - curl $SERVER_URL

    environment:
      SERVER_URL: ${{ services.api.interfaces.main.url }}

services:
  api:
    image: heroku/nodejs-hello-world
    interfaces:
      main: 3000

interfaces:
  api: ${{ services.api.interfaces.main.url }}
