name: examples/scheduled-tasks
description: Example application that calls the API once per 5 minutes and prints the results; showcasing Tasks (cron jobs)
homepage: https://github.com/architect-team/architect-cli/tree/master/examples/scheduled-tasks

parameters:

tasks:
  curler:
    schedule: "*/5 * * * ?"
    image: ellerbrock/alpine-bash-curl-ssl # useful public image with bash and curl pre-installed
    command:
      - sh
      - -c
      - curl ${{ environment.ingresses['architect-ryan/scheduled-tasks']['api'].url }}

services:
  api:
    image: heroku/nodejs-hello-world
    interfaces:
      main: 3000

interfaces:
  api: ${{ services.api.interfaces.main.url }}
