name: scheduled-tasks
description: Example application that supports manual tasks and prints the results
homepage: https://github.com/architect-team/architect-cli/tree/main/examples/scheduled-tasks

tasks:
  curler:
    image: ellerbrock/alpine-bash-curl-ssl # useful public image with bash and curl pre-installed
    schedule: '0 0 * * *' # every day at 12:00am
    command:
      - sh
      - -c
      - curl $SERVER_URL

    environment:
      SERVER_URL: ${{ services.api.interfaces.main.url }}

services:
  api:
    build:
      context: ../hello-world
    interfaces:
      main: 3000

interfaces:
  api:
    url: ${{ services.api.interfaces.main.url }}
    ingress:
      subdomain: api
