name: examples/basic-task
description: Example application that calls the API once per 5 minutes and prints the results; showcasing Tasks (cron jobs)

parameters:

tasks:
  curler:
    schedule: "*/5 * * * ?"
    image: ellerbrock/alpine-bash-curl-ssl # useful public image with bash and curl pre-installed
    command:
      - sh
      - -c
      - curl $SERVER_URL

    environment:
      SERVER_URL: ${{ services.api.interfaces.main.url }}

services:
  api:
    image: heroku/nodejs-hello-world
    interfaces:
      main: 3000

interfaces:
  api: ${{ services.api.interfaces.main.url }}
