#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx eslint --fix --max-warnings=0 --config .eslintrc.js --no-error-on-unmatched-pattern $(git diff --name-only --cached -- '*.ts' '*.js')

npm run test
npm run check-circular
