name: Publish GitHub Actions and CircleCI Orb

on:
  push:
    paths:
      - 'circleci-orbs/preview.yml'
    branches:
      - master

jobs:
  publish_circleci_orb:
    name: Publish CircleCI Orb
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: circleci-orb
      - run: sudo snap install circleci
      - run: circleci orb validate ./circleci-orbs/preview.yml --host https://circleci.com --token ${{ secrets.CIRCLE_TOKEN }}
      - run: circleci orb publish ./circleci-orbs/preview.yml architect/preview@dev:master --host https://circleci.com --token ${{ secrets.CIRCLE_TOKEN }}
      - run: circleci orb publish promote architect-io/preview@dev:master patch --host https://circleci.com --token ${{ secrets.CIRCLE_TOKEN }}
