name: Register Example Components

on:
  push:
    paths:
      - "examples/**/*"

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.detect.outputs.matrix }}
    steps:
      - name: Install jq library
        run: apt-get update && apt-get install jq
      - id: detect
        name: Detect which examples have changes
        run: >
          export CHANGES=$(for path in $(find ./examples/*/architect.yml -type f -maxdepth 0 -exec dirname {} \; | uniq); do test $(git diff-tree --name-only --no-commit-id -r HEAD "$path" | wc -c) -ne 0 && echo $path; done)
          echo "::set-output name=matrix::$(jq -n --arg v "$CHANGES" '{"component_path": $v | split("\n") }')"
  register-components:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.detect-changes.outputs.matrix)}}
    steps:
      - name: Register component
        run: echo ${{ matrix.component_path }}
