name: Test superset deployment

on:
  push:
    branches:
      - superset-updates # TODO: remove when done testing
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  # test_local:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '16'
  #         cache: 'npm'
  #     - run: sudo apt-get update && sudo apt-get install curl
  #     - run: npm install -g @architect-io/cli@1.28.0-arc-detached-testing.1 # TODO: undo when the exec file remove problem is fixed - https://gitlab.com/architect-io/architect-cli/-/issues/560
  #     - run: architect --version
  #     - run: architect config:set registry_host registry.dev.architect.io
  #     - run: architect config:set api_host https://api.dev.architect.io
  #     - run: architect config:set log_level debug
  #     - run: architect login -e ${{ secrets.ARCHITECT_EMAIL }} -p ${{ secrets.ARCHITECT_PASSWORD }}
  #     - run: git clone -b superset-updates https://github.com/architect-team/architect-cli.git # TODO: remove branch when this is merged
  #     - run: docker volume create volume-key
  #     - run: architect link examples/hello-world/architect.yml
  #     - run: architect dev -e superset architect-cli/test/mocks/superset/architect.yml --browser=false -s param_unset=test > ./tmp.txt 2>&1 &
  #     - run: sh architect-cli/scripts/server_online.sh
  #     - run: echo "Finished waiting"
  #     - name: Check that the app is accessible locally
  #       run: architect exec -e superset superset.services.stateless-app -- sh -c "curl --fail -S -I https://hello.localhost.architect.sh:443/"

  test_remote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - run: sudo apt-get update && sudo apt-get install curl
      - run: npm install -g @architect-io/cli
      - run: architect --version
      - run: architect config:set registry_host registry.dev.architect.io
      - run: architect config:set api_host https://api.dev.architect.io
      - run: architect config:set log_level debug
      - run: architect login -e ${{ secrets.ARCHITECT_EMAIL }} -p ${{ secrets.ARCHITECT_PASSWORD }}
      # - run: git clone -b superset-updates https://github.com/architect-team/architect-cli.git # TODO: remove branch when this is merged
      # - run: architect env:create do-k8s || exit 0 # TODO: remove once 409s can be ignored - https://gitlab.com/architect-io/architect-cli/-/issues/556
      # - run: architect deploy -a architect-ci --auto-approve -e do-k8s architect-cli/test/mocks/superset/architect.yml -s param_unset=test
      # - run: sleep 180 # TODO: change account back to architect-ci and environment back to example-environment
      - run: curl --insecure --fail -S -I https://hello.do-k8s.architect-ci.dev.arcitect.io/ || exit 1
      - name: Ensure that cert exists for deployed service
        run: |
          export CERT_DATA=$(openssl s_client -showcerts -connect hello.do-k8s.architect-ci.dev.arcitect.io:443 </dev/null | openssl x509 -noout -issuer) # TODO: update app domain, parameterize
          if [[ "$CERT_DATA" = "issuer=C = US, O = Let's Encrypt, CN = R3" || "$CERT_DATA" = "issuer=C = US, O = (STAGING) Let's Encrypt, CN = (STAGING) Artificial Apricot R3" ]]; then echo "Valid cert generated"; else exit 1; fi
      - name: Check that network policies are being enforced in the cluster
        run: architect exec -a architect-ci -e do-k8s superset.services.stateful-api -- sh -c  "curl --connect-timeout 5 --insecure -L -I http://hello-world--api:3000/ || true" > curl_test.txt
          # echo "CURL_TEST"
          # cat curl_test.txt
          # echo "CURL_TEST"
          # if [[ $(cat curl_test.txt) == *"Connection timeout"* ]]; then echo 0; else echo 1; fi
