name: Test superset deployment

on:
  push:
    branches:
      - superset-updates # TODO: update

jobs:
  # test_local:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '16'
  #         cache: 'npm'
  #     # TODO: name steps
  #     - run: sudo apt-get update && sudo apt-get install curl
  #     - run: npm install -g @architect-io/cli
  #     - run: architect --version
  #     - run: architect config:set registry_host registry.dev.architect.io
  #     - run: architect config:set api_host https://api.dev.architect.io
  #     - run: architect config:set log_level debug
  #     - run: architect login -e ${{ secrets.ARCHITECT_EMAIL }} -p ${{ secrets.ARCHITECT_PASSWORD }}
  #     - run: git clone -b superset-updates https://github.com/architect-team/architect-cli.git # TODO: update branch
  #     - run: docker volume create volume-key
  #     - run: architect link examples/hello-world/architect.yml
  #     - run: architect dev -e superset architect-cli/test/mocks/superset/architect.yml --browser=false -s param_unset=test > ./tmp.txt 2>&1 & # TODO: make ticket for compose file being deleted when the -d flag is used
  #     - run: sh architect-cli/scripts/server_online.sh
  #     - run: echo "Finished waiting"
  #     - run: tail -f ./tmp.txt &
  #     - run: architect exec -e superset superset.services.stateless-app -- sh -c "curl --fail -S -I https://hello.localhost.architect.sh:443/"

  test_remote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - run: apt install curl
      - run: npm install -g @architect-io/cli
      - run: architect --version
      - run: architect config:set registry_host registry.dev.architect.io
      - run: architect config:set api_host https://api.dev.architect.io
      - run: architect config:set log_level debug
      - run: architect login -e ${{ secrets.ARCHITECT_EMAIL }} -p ${{ secrets.ARCHITECT_PASSWORD }}
      - run: git clone -b superset-updates https://github.com/architect-team/architect-cli.git # TODO: update branch
      - run: architect register -a architect-ci examples/hello-world/architect.yml # TODO: update account and environment names here
      - run: architect deploy -a architect-ci --auto-approve -e example-environment architect-cli/test/mocks/superset/architect.yml -s param_unset=test # TODO: deploy when we merge to rc
      - run: sleep 180
      - run: curl --insecure --fail -S -I https://hello.example-environment.architect-ci.dev.arcitect.io/ || exit 1
      - run: export CERT_DATA=$(openssl s_client -showcerts -connect example-environment.architect-ci.dev.arcitect.io:443 </dev/null | openssl x509 -noout -issuer) # TODO: update app domain
      - run: if [[ "$CERT_DATA" = "issuer=C = US, O = Let's Encrypt, CN = R3" || "$CERT_DATA" = "issuer=C = US, O = (STAGING) Let's Encrypt, CN = (STAGING) Artificial Apricot R3" ]]; then echo "Valid cert generated"; else exit 1; fi
      # TODO: architect exec to hello-world instance and attempt to get a container it shouldn't be able to access, ex stateful-app
      # (curl -I -L  google.com || true) > test.txt
      - run: |
          architect exec -e superset superset.services.stateful-api -- sh -c "(curl --insecure -L -I https://hello.localhost.architect.sh:443/ || true) > curl_test.txt"
          exit $?
      # TODO: deploy to a different environment based on the branch name or something?
