name: Rebuild Architect docs

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: docs website re-build
        run: curl -X POST ${{ secrets.NETLIFY_BUILD_HOOK_URL }}
